# Generated by Django 5.2.7 on 2025-11-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('bol_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('bol_folio', models.IntegerField(blank=True, null=True)),
                ('bol_fecha', models.DateTimeField(blank=True, null=True)),
                ('bol_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bol_despacho', models.CharField(blank=True, max_length=100, null=True)),
                ('bol_fecha_venc', models.DateTimeField(blank=True, null=True)),
                ('bol_pdf', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoletaPago',
            fields=[
                ('bolpago_id', models.AutoField(primary_key=True, serialize=False)),
                ('bolpago_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'boleta_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('caja_id', models.AutoField(primary_key=True, serialize=False)),
                ('caja_nom', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_nom', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_id', models.AutoField(primary_key=True, serialize=False)),
                ('cli_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('cli_rut', models.CharField(blank=True, max_length=20, null=True)),
                ('cli_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cli_mail', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('con_id', models.AutoField(primary_key=True, serialize=False)),
                ('con_nom', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'condicion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('est_id', models.AutoField(primary_key=True, serialize=False)),
                ('est_nom', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('inv_id', models.AutoField(primary_key=True, serialize=False)),
                ('inv_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('inv_costeo_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('inv_por_vender_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('inv_utilidad_neta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('inv_margen_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_codigobarra', models.CharField(blank=True, max_length=50, null=True)),
                ('prod_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prod_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('prod_prec_compra_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prod_prec_venta_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prod_prec_venta_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prod_afecto_iva', models.BooleanField(blank=True, null=True)),
                ('prod_tipo_unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('prod_marca', models.CharField(blank=True, max_length=50, null=True)),
                ('prod_talla', models.CharField(blank=True, max_length=20, null=True)),
                ('prod_color', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('rol_nom', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('suc_id', models.AutoField(primary_key=True, serialize=False)),
                ('suc_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('suc_direc', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('tipopago_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipopago_nom', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usu_nom', models.CharField(max_length=255)),
                ('usu_mail', models.CharField(max_length=255, unique=True)),
                ('usu_pass', models.CharField(max_length=255)),
            ],
        ),
    ]
